export const SHIPPING_TOKENS = {
    SHIPPING_FACTORY: Symbol('SHIPPING_FACTORY'),
    SHIPPING_SERVICE: Symbol('SHIPPING_SERVICE'),
    REPOSITORIES: {
        SHIPPING_QUERY: Symbol('SHIPPING_QUERY_REPOSITORY'),
        SHIPPING_COMMAND: Symbol('SHIPPING_COMMAND_REPOSITORY'),
    },
    SERVICE_PROVIDERS: {
        GHTK: Symbol('SHIPPING_SERVICE_GHTK'),
    },
};
