export const DELIVERY_TOKENS = {
    COMMAND_REPOSITORY: Symbol('DELIVERY_COMMAND_REPOSITORY'),
    QUERY_REPOSITORY: Symbol('DELIVERY_QUERY_REPOSITORY'),
    QUERY_SERVICE: Symbol('DELIVERY_QUERY_SERVICE'),
    COMMAND_SERVICE: Symbol('DELIVERY_COMMAND_SERVICE'),
};
